name: pedometer
description: Pedometer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sensors_plus: ^1.4.0
  format: ^1.2.0
  numdart: ^1.0.0
  scidart: ^0.0.2-dev.12
  fmin: ^0.1.0
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/